### ISSUE TITLE
Not working demos - missing resources

### ISSUE THREAD

**Issue by ghost** [DJMaster/csfml-fpc#1]
Hello,

In all demo packages (sfml-csfml_demos-win32.zip etc.) is missing folder "resources" with fonts, graphics, shaders and so.

And can you please provide also demos source codes?

**Comment by DJMaster** [comment]
Thank You for reporting it, zip/7z files updated.
Demos source codes published.

**Comment by ghost** [comment]
Perfect, thank you.
